version: "3"
services:
    frontend:
        build:
            context: frontend/
        ports:
            - ${FRONTEND_PORT}:80
        depends_on:
            - backend

    backend:
        environment:
            - DB_URI=${DB_URI}
            - API_PORT=${BACKEND_PORT}
            - API_SIGN_SECRET=${API_SIGN_SECRET}
            - API_ORIGIN_URL=${API_ORIGIN_URL}
            - API_ENV=${API_ENV}
        build:
            context: backend/
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}