version: "3"

services:
    frontend:
        build:
            context: frontend/
        ports:
            - ${FRONTEND_PORT}:80
        depends_on:
            - backend

    backend:
        environment:
            - DB_URI=${DB_URI}
            - PORT=${BACKEND_PORT}
            - SIGN_SECRET=${SIGN_SECRET}
        build:
            context: backend/
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}