export const TimerActionsTypes = {
	LOGIN_GET_SETTINGS: "LOGIN_GET_SETTINGS",
	CLEAR_SETTINGS: "CLEAR_SETTINGS",
	CHANGE_DEFAULT_TIME: "CHANGE_DEFAULT_TIME",
	CHANGE_LONG_BREAK: "CHANGE_LONG_BREAK",
	CHANGE_SHORT_BREAK: "CHANGE_SHORT_BREAK",
	CHANGE_AUTH_FLAG: "CHANGE_AUTH_FLAG",
	CHANGE_TICKTRACK: "CHANGE_TICKTRACK",
	GET_SETTINGS: "GET_SETTINGS",
	CHANGE_TO_POMODORO: "CHANGE_TO_POMODORO",
	CHANGE_TO_SHORT_BREAK: "CHANGE_TO_SHORT_BREAK",
	CHANGE_TO_LONG_BREAK: "CHANGE_TO_LONG_BREAK",
	CHANGE_STATUS: "CHANGE_STATUS",
	CHANGE_TIMER_MODE: "CHANGE_TIMER_MODE",
	CHANGE_TIMER_ACTION: "CHANGE_TIMER_ACTION"
}

export enum EnumTimerMode {
	POMODORO = "POMODORO",
	LONG_BREAK = "LONG_BREAK",
	SHORT_BREAK = "SHORT_BREAK"
}

export enum EnumTimerAction {
	START = "START",
	STOP = "STOP",
	PAUSE = "PAUSE"
}
