basePath: /
definitions:
  internal_handler.HealthReport:
    type: object
  internal_handler.ResponseTemplate:
    properties:
      data:
        type: object
      message:
        type: string
    type: object
  tomato-timer_backend_internal_handler.HealthReport:
    type: object
  tomato-timer_backend_internal_handler.ResponseTemplate:
    properties:
      data:
        type: object
      message:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API Server for Tomato-timer
  title: Tomato-timer backend
  version: "1.0"
paths:
  /health-check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler.HealthReport'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handler.HealthReport'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handler.HealthReport'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_handler.HealthReport'
        default:
          description: ""
          schema:
            type: string
      summary: Show a service health
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Email, max email length (rfc3696) 320 characters
        in: body
        minLength: 5
        name: Email
        required: true
        schema:
          type: string
      - description: User Password
        in: body
        minLength: 8
        name: Password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tomato-timer_backend_internal_handler.ResponseTemplate'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/tomato-timer_backend_internal_handler.ResponseTemplate'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/tomato-timer_backend_internal_handler.ResponseTemplate'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tomato-timer_backend_internal_handler.ResponseTemplate'
        default:
          description: ""
          schema:
            type: string
      summary: Show a service health
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Email, max email length (rfc3696) 320 characters
        in: body
        minLength: 5
        name: Email
        required: true
        schema:
          type: string
      - description: User Password
        in: body
        minLength: 8
        name: Password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tomato-timer_backend_internal_handler.ResponseTemplate'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/tomato-timer_backend_internal_handler.ResponseTemplate'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/tomato-timer_backend_internal_handler.ResponseTemplate'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tomato-timer_backend_internal_handler.ResponseTemplate'
        default:
          description: ""
          schema:
            type: string
      summary: Show a service health
swagger: "2.0"
