name: build_test

on:
  push:
    branches: [ main ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: "Job status"
        run: echo "⚡️ ${{ job.name }} status is ${{ job.status }}."

  build_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: go build -v -o main ./cmd/main.go
      - name: Test
        run: go test -v ./...
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: "Job status"
        run: echo "⚡️ ${{ job.name }} status is ${{ job.status }}."
