name: frontend

on:
  push:
    branches: [ main ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: "Job status"
        run: echo "⚡️ ${{ job.name }} status is ${{ job.status }}."