name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: cd ./backend &&  go build -v -o main ./cmd/main.go 

    - name: Test
      run: go test -v ./...
      
    - name: List files in the repository
      run: ls ${{ github.workspace }}
      
    - name: "Job's status"
      run: echo "🍏 This job's status is ${{ job.status }}."
